language: node_js
node_js:
  - stable
install:
  - npm install
deploy:
  provider: npm
  email: "pasquale.delucia96@gmail.com"
  api_key: "fa2de90a-dfab-4b33-ba45-c09cdeefef1c"
  on:
    tags: true
    branch: production
